apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nrhwva200-python 
  janus-idp.io/tekton: nrhwva200-python
  backstage.io/kubernetes-id: nrhwva200-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nrhwva200-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml