apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nrhwva200-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nrhwva200-python 
  name: nrhwva200-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nrhwva200-python 
